services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_DB=dev-mem
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/keycloak-realm-config.json
    volumes:
      - ./data/import:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    ports:
      - "8085:8080"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/individuals
      - KEYCLOAK_CLIENT_ID=individuals-api
      - KEYCLOAK_CLIENT_SECRET=5N7lXXF9M56qA77Do0c0lsRcQzU3gk4v
    volumes:
      - ./keycloak-realm-config.json:/keycloak-realm-config.json
    ports:
      - "8090:8090"
    depends_on:
      - keycloak
    networks:
      - app_network

networks:
  app_network:
    driver: bridge