server:
  port: 8080

spring:
  webflux:
    base-path: /api
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/individuals
          jwk-set-uri: http://localhost:8081/auth/realms/individuals/protocol/openid-connect/certs
          jwks: http://localhost:8081/auth/realms/individuals/protocol/openid-connect/token
      client:
        registration:
          keycloak:
            client-id: individuals-api
            client-secret: 5N7lXXF9M56qA77Do0c0lsRcQzU3gk4v
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/auth/realms/individuals
            user-name-attribute: email

keycloak:
  realm: individuals
  auth-server-url: http://localhost:8081/auth


