server:
  port: 8089

spring:
#  main:
#    lazy-initialization: true
#  lifecycle:
#    timeout-per-shutdown-phase: 60s
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: email

KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/individuals
KEYCLOAK_CLIENT_ID: individuals-api
KEYCLOAK_CLIENT_SECRET: 5N7lXXF9M56qA77Do0c0lsRcQzU3gk4v

keycloak:
  admin-username: admin
  admin-password: admin
  realm: individuals
  auth-server-url: http://keycloak:8080

